[package]
name = "stream-video"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3.30"
openh264 = "0.5.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
tokio-tungstenite = "0.21.0"
tokio-util = "0.7.10"
tungstenite = "0.21.0"
websocket = "0.27.0"
